### ISSUE TITLE
allow configuration of timeout of GetProjectSettings call

### ISSUE THREAD

**Issue by beerockxs** [qwc-services/qwc-config-service#3]
The timeout for the GetProjectSettings call is hardcoded to 30 seconds in line 116 of ogc_service_permission. For complex projects, this is not long enough. Please allow the configuration of this timeout parameter.

**Comment by manisandro** [comment]
qwc-config-service is deprecated and replaced by qwc-config-generator. I've reported the issue there [1]

[1] https://github.com/qwc-services/qwc-config-generator/issues/25
